### ISSUE TITLE
OpenMVG : Tutorial demo Path issue, chmod needed

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#6]
Hi Pierre Yves,

Me again ;-) Ok so after all the last days spend in compiling, I decided to make my first step in photogrammetry ! So, I launch the tutorial_demo.py and  there is an issue with the path, I solved it with : 
```
chmod +x /usr/local/etc/openMVG
```
Otherwise it was not able to find the sensor db ;-)

Kenavo ;-)

Stéphane

**Comment by pyp22** [comment]
Hi Stephane, 
I suppose you're sudoing if that worked. This dir does not contain any binary so a +x is not really revelant. I modified the script to force it to use $HOME instead of relative path from binary localization. See commit https://github.com/pyp22/NuxSFM-2.0/commit/e0431f54c797d3d152ceb7c538bc04583a48068c.

Pse tell me if it works for you.

Thanks a lot for all your feedbacks by the way ;-)

Kenavo ;-)

PY

**Comment by stephane-lb** [comment]
Hi Pierre-Yves,

You are more than welcome, you did a fantastic work, so that's normal for me to provide you feedbacks to help you a little bit.

In the last script you will have to change the line 31 ( tutorial_demo.py ) otherwise it is not cloning the ImageSet at the good place.

I restore the rights as it was previously ( chmod 544) and I got this error : 
```
Invalid input database: /usr/local/etc/openMVG/sensor_width_camera_database.txt, please specify a valid file.
```

Have a nice day,

Stephane

**Comment by pyp22** [comment]
Hi Stephane, yep correct. Saw that too when running as normal user who can not read /usr/local/etc/openMVG. In fact you were right ^^ Perms pb. Fixing it.

I'm running root. I'm an old linuxian and i hate sudo ^^ but wanyway will test averything as normal user from now. I'll take a look to line 31 too.

Thanks,

PY

**Comment by pyp22** [comment]
perms pb should be solved by commit https://github.com/pyp22/NuxSFM-2.0/commit/e0431f54c797d3d152ceb7c538bc04583a48068c. The previous MV was giving wrong perms. Solved in commit https://github.com/pyp22/NuxSFM-2.0/commit/e0431f54c797d3d152ceb7c538bc04583a48068c. Tested with norm user too.

Instead of recompiling & reinstalling you can do a chmod 1777 /usr/local/etc/openMVG. 

Kenavo,

PY

**Comment by pyp22** [comment]
commit https://github.com/pyp22/NuxSFM-2.0/commit/9929beb930117cd955000fda183d59bdd9579f74 to force tutorial_demo.py to use user home dir. Tested here on norm user.

**Comment by stephane-lb** [comment]
Hi Pierre Yves,

I am trying to force myself to reinstalling each time, I think it is a good way to give you feedbacks.

Still have this line, not sure it is normal ( except if I chmod )
```
Invalid input database: /usr/local/etc/openMVG/sensor_width_camera_database.txt, please specify a valid file
```

Kenavo ;-)

Stephane

**Comment by pyp22** [comment]
Thanks a lot. What i did here is rm -fr /usr/local/etc/openMVG and resintall it from fresh built. Then ran tutorial as a non root user. 

pacman -dd -R openMVG then  pacman -U openMVG-v0.9.r0.gf0889f0-1-x86_64.pkg.tar.xz
(version might differ for you as you're compiling it yourselves).

It worked for me. I think simply reinstalling a fresh built over the previous one is not enough. I suppose its says somehting about perms changes when doing that, isn't it ?

Regards

PY

**Comment by stephane-lb** [comment]
Still the same here. No worry, I know that I just have to add the +x on the directory.

Have a good evening,

Stephane

**Comment by pyp22** [comment]
ok thanks. I'm gonna keep this one opened by now until i discover what's happening as i can't reproduce this error what may be encountered by other users. To go beyond, i'll write  a short wiki page for you about openMVG & openMVS run in the distro. I'm looking forward to see your own rescontructions ;-)

Have a good evening too. I stop for this evening. Week has been hard ;-)

Kenavo & thank you agn.

PY

**Comment by stephane-lb** [comment]
Thank you so much for the wiki, I was looking in an How to this afternoon !

Have a great week-end and see you Monday,

Stéphane

**Comment by pyp22** [comment]
Here is the short one. https://github.com/pyp22/NuxSFM-2.0/wiki/Testing-with-openMVG-&-openMVS

Of course read openMVG & openMVS docs to change scripts internal values.

Have a nice WE.

PY

**Comment by stephane-lb** [comment]
Thank you very much !
